on:
  push:
    branches:
      - main
    paths:
      - 'api_go365/**'
      - 'api_superb/**'
      - 'api_2UCenter/**'
      - 'api_TTN_Pluss/**'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [api_go365, api_superb, api_2UCenter, api_TTN_Pluss]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy ${{ matrix.folder }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          local-dir: ./${{ matrix.folder }}/
          server-dir: /httpdocs/${{ matrix.folder }}/